### ISSUE TITLE
was ist das jetzt wieder geisteskrankes?

### ISSUE THREAD

**Issue by mnlmaier** [bumscode/aktivierbare-eigenleistungen-pro-max-2000#1]
boys, was geht, was baut ihr? kaum ist man mal n monat raus aus der company... :D

**Comment by T0TProduction** [comment]
Hackathon letsgoooo

**Comment by lostdesign** [comment]
Timetracking goes brrr ![image](https://user-images.githubusercontent.com/5164617/159980793-f0cfba0c-1e93-4525-ade7-9c8a30a5d7c4.jpeg)

**Comment by mnlmaier** [comment]
Ich hab nur die Dino Sprites in der Readme gesehen und war intrigued 👀
